export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const REQUEST_COMMENTS_FAILED = "REQUEST_COMMENTS_FAILED";

export const SEND_POST_REQUEST = "SEND_POST_REQUEST";
export const SEND_POST = "SEND_POST";
export const SEND_POST_FAILED = "SEND_POST_FAILED";
